{% set name = "greedy" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06f24b48972ac2fa60cfb5ba6f1fee97a754641c771d42390d515f04eb2f69dc

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - geopandas
    - networkx
    - libpysal

test:
  imports:
    - greedy

about:
  home: https://github.com/martinfleis/greedy
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Greedy (topological) coloring for GeoPandas'

  description: |
    greedy is a Python package which brings topological (greedy) coloring
    to GeoPandas. It offers several coloring strategies, all accessible using
    one line of code.
  doc_url: https://martinfleis.github.io/greedy/
  dev_url: https://github.com/martinfleis/greedy

extra:
  recipe-maintainers:
    - martinfleis
